analogdevicesinc/aditof-sdk-rework

LICENSE
Proprietary license used for this rework.  Will this update the github project license type, in no we may need to create a new repository from scratch?
=> Change license type to proprietary

sdk/include/aditof/frame.h, sdk/src/frame.cpp, sdk/src/frame_impl.cpp, sdk/src/frame_impl.h
=> sdk: Add 'attributes' to a frame

sdk/include/aditof/frame_operations.h
Signed-off-by: SeptimiuVana <vana.septimiu@analog.com>
=> Update frame_operations.h file to include frameDataDetails

apps/server/server.h, sdk/src/connections/network/network.cpp
=> Fix number of sent bytes on network

sdk/CMakeLists.txt
=> Update depth_compute libraries include for windows

sdk/src/connections/target/adsd3100_sensor.h
Signed-off-by: Virgil Litan <virgil.litan@analog.com>
=> add embedded header to all modes

sdk/src/connections/target/adsd3100_sensor.h
Signed-off-by: Virgil Litan <virgil.litan@analog.com>
=> add raw to mode 5

examples/data_collect/main.cpp
=> Update data_collect to use ip

CMakeLists.txt
=> Set USE_ITOF to on in CMakeLists.txt

examples/data_collect/main.cpp
=> examples/data_collect: Add missing chrono header

examples/CMakeLists.txt, scripts/nxp/setup.sh
=> Add script for nxp build

sdk/src/system_impl.cpp
=> sdk: Don't create camera instance if network connection failed

CMakeLists.txt, sdk/src/connections/offline/offline_depth_sensor.cpp, sdk/src/connections/offline/offline_sensor_enumerator.cpp
And don't hardcode the name of the build diretory
=> sdk: Setup a resources dir in build folder

examples/first-frame/main.cpp, sdk/src/cameras/itof-camera/camera_itof.cpp, sdk/src/cameras/itof-camera/camera_itof.h, sdk/src/cameras/itof-frame/frame_impl.cpp, sdk/src/connections/offline/offline_depth_sensor.h, sdk/src/connections/target/adsd3100_sensor.cpp, sdk/src/connections/target/adsd3100_sensor.h
Implement necessary changes in order to run mode 5 .
=> Mode5 bringup 

scripts/windows/setup_project.bat
=> Remove OpenCV and python bindings from windows build script

examples/data_collect/main.cpp, examples/first-frame-network/main.cpp, examples/first-frame/main.cpp, sdk/src/cameras/itof-camera/camera_itof.cpp
Initialize depth compute library only once (in camera->start() )
=> Single tofi init

sdk/src/connections/offline/offline_depth_sensor.cpp
Signed-off-by: Virgil Litan <virgil.litan@analog.com>
=> offline sensor: mock program() returns OK

README.md, doc/itof/nxp_build_instructions.md
=> Add build instructions for nxp and itof camera

examples/data_collect/main.cpp
=> Shorten help message data_collect

sdk/src/cameras/itof-camera/camera_itof.cpp
=> camera_itof: Use 'this' pointer when binding class methods

sdk/src/cameras/itof-camera/camera_itof.cpp, sdk/src/cameras/itof-camera/imx/sensor_enumerator_imx.cpp, sdk/src/cameras/itof-camera/imx/target_definitions.h
=> sdk: src: camera: itof-camera: Enable EEPROM interface

bindings/python/aditofpython.cpp, sdk/src/connections/target/adsd3100_sensor.cpp
1. Update direct sensor register read/write functions
2. Add regread, regwrite, regwriteburst functions in Python bindings
=> Sensor direct reg access

sdk/src/cameras/itof-camera/camera_itof.cpp
=> sdk: camera: camera_itof: Fix unnecessary open bracket

apps/uvc-app/uvc-gadget.cpp
=> uvc-gadget.cpp: fix cast error in storage write function

sdk/include/aditof/storage_interface.h, sdk/src/connections/network/network_storage.cpp, sdk/src/connections/network/network_storage.h, sdk/src/connections/target/eeprom.cpp, sdk/src/connections/target/eeprom.h, sdk/src/connections/usb/linux/usb_storage_linux.cpp, sdk/src/connections/usb/macos/usb_storage_macos.cpp, sdk/src/connections/usb/usb_storage.h, sdk/src/connections/usb/windows/usb_storage_windows.cpp
Method is needed by ModuleMemory
=> Storage add capacity

sdk/src/cameras/itof-camera/camera_itof.cpp
=> camera_itof.cpp: Move initComputeLibrary from start to setFrameType

sdk/src/cameras/itof-camera/camera_itof.cpp
=> sdk:itof-camera: camera_itof.cpp: Add checks for eeprom availability

sdk/CMakeLists.txt
=> sdk/CMakeLists.txt: add path to TOF_Calibration_Types.h

sdk/src/cameras/itof-camera/adsd3100_configuration.cpp, sdk/src/cameras/itof-camera/adsd3100_configuration.h, sdk/src/cameras/itof-camera/calibration_itof.cpp, sdk/src/cameras/itof-camera/calibration_itof.h
=> calibration_tof: Add ADSD3100Configuration dependecy

sdk/src/cameras/itof-camera/calibration_itof.cpp
=> calibration_itof.cpp: implement writeSettings function

sdk/src/cameras/itof-camera/calibration_itof.cpp, sdk/src/cameras/itof-camera/calibration_itof.h
=> calibration_itof: Implement writeConfiguration() and writeConfigBlock()

sdk/CMakeLists.txt
=> sdk/CMakeLists.txt: minor fix in path

sdk/src/cameras/itof-camera/calibration_itof.cpp, sdk/src/cameras/itof-camera/calibration_itof.h
=> sdk: cameras: calibration_itof: Implement write calibration functions

sdk/src/cameras/itof-camera/adsd3100_configuration.cpp, sdk/src/cameras/itof-camera/adsd3100_configuration.h, sdk/src/cameras/itof-camera/calibration_itof.cpp, sdk/src/cameras/itof-camera/calibration_itof.h, sdk/src/cameras/itof-camera/camera_itof.cpp, sdk/src/cameras/itof-camera/camera_itof.h
=> Itof calibration class

sdk/src/cameras/itof-camera/adsd3100_configuration.cpp, sdk/src/cameras/itof-camera/calibration_itof.cpp, sdk/src/cameras/itof-camera/configuration.h
=> Minor fixes for nxp build

CMakeLists.txt, sdk/CMakeLists.txt
=> sdk/CMakeLists.txt: define libs path to be visible in the parent scope

sdk/src/cameras/itof-camera/camera_itof.cpp
=> camera_itof.cpp: clear frame type vector when changing frame

examples/tof-viewer/src/ADIMainWindow.cpp
=> tof-viewer/ADIMainWindow.cpp: request frame sooner to update frame data

bindings/python/examples/first_frame/first_frame.py
=> bindings/python: update first-frame example

examples/CMakeLists.txt
=> examples: Disable aditof-demo and aditof-test for now

README.md
=> README.md: remove duplicated windows build instructions

cmake/aditof-setup.iss.cmakein
=> ci/windows: Include data_collect & first-frame in windows installer

sdk/src/cameras/itof-camera/camera_itof.cpp, sdk/src/cameras/itof-camera/mode_info.cpp, sdk/src/cameras/itof-camera/mode_info.h, sdk/src/connections/offline/offline_depth_sensor.h, sdk/src/connections/target/adsd3100_sensor.h
=> Use 3 modes only

sdcard-images-utils/nxp/deboot.sh
=> sdcard-images-utils: Add user to disk group

examples/data_collect/main.cpp
=> data_collect: Allow values 3, 5, 7, 10 for -m cmd line param

doc/itof/windows_build_instructions.md
=> doc/itof: update windows build instructions for vs 2019

ci/appveyor/install_websockets.bat, ci/travis/lib.sh, doc/itof/linux_build_instructions.md, doc/itof/nxp_build_instructions.md, doc/linux/build_instructions.md, scripts/windows/setup_project.bat
=> Discard ssl dependency

doc/itof/linux_build_instructions.md, doc/itof/nxp_build_instructions.md, doc/itof/windows_build_instructions.md, doc/linux/build_instructions.md, doc/windows/build_instructions.md
=> doc: Remove the rest of open SSL references in doc

examples/data_collect/main.cpp, sdk/src/cameras/itof-camera/camera_itof.cpp, sdk/src/cameras/itof-camera/camera_itof.h, sdk/src/cameras/itof-camera/module_memory.cpp, sdk/src/cameras/itof-camera/module_memory.h
=> Dump ccb to file data collect

examples/data_collect/main.cpp
Without this fix data_collect would throw SEG_FAULT when
run on target.
=> examples: data_collect: main.cpp: Fix mode qmp on data_collect

examples/tof-viewer/src/ADIView.cpp
Fix for issue #168, GUI display wraparound.
=> Clip active brightness to 8bit max display range

examples/data_collect/main.cpp, examples/tof-viewer/src/ADIMainWindow.cpp
=> examples: Fix call to localtime_s not building on linux (NXP)

sdcard-images-utils/nxp/deboot.sh, sdcard-images-utils/nxp/runme.sh
Use ext4 instead of ext2 and add -o barrier=0.
=> Improve deboostrap speed

sdcard-images-utils/nxp/README.md, sdcard-images-utils/nxp/deboot.sh, sdcard-images-utils/nxp/runme.sh
DISTRO_MIRROR: The location of Ubuntu apt repository.
NXP_GIT_LOCATION: The location of NXP git repositories.
TOF_GIT_LOCATION: The location of TOF git repository.
Set these variable to use local mirror location and speed up package/srouce download
=> Add some BASH variables to help build.

doc/windows/build_instructions.md
=> doc: Document the option to use Depth Compute stubs

README.md
=> Readme: Remove warning about this project not being ready to use

bindings/python/examples/first_frame/first_frame.py
Added this line to get first_frame.py working
=> Added line to first frame to get valid frames

examples/CMakeLists.txt, sdk/src/connections/usb/linux/usb_depth_sensor_linux.cpp, sdk/src/connections/usb/linux/usb_linux_utils.cpp, sdk/src/connections/usb/linux/usb_linux_utils.h, sdk/src/connections/usb/linux/usb_sensor_enumerator.cpp, sdk/src/connections/usb/linux/usb_storage_linux.cpp, sdk/src/connections/usb/usb_utils.cpp, sdk/src/connections/usb/usb_utils.h
USB communication on Linux doesn't work yet. I still need to figure out why.
But this PR makes possible for the SDK to build in case someone want to use the network communication.
Also the Tof Viewer has been disabled for now until we make it build on linux.
So this is the 1st step towards making entire project build on Linux.
=> First linux usb implementation

README.md, bindings/ros/CMakeLists.txt, bindings/ros/README.md, bindings/ros/aditof_roscpp/CMakeLists.txt, bindings/ros/aditof_roscpp/include/aditof_roscpp/aditof_utils.h, bindings/ros/aditof_roscpp/launch/camera_node.launch, bindings/ros/aditof_roscpp/package.xml, bindings/ros/aditof_roscpp/src/aditof_utils.cpp, bindings/ros/aditof_roscpp/src/camera_node.cpp, bindings/ros/ros_setup.bash
Signed-off-by: rbudai98 <robert.budai@analog.com>
=> ros: cmakelist update and ir-depth node publishing

sdk/src/connections/target/adsd3100_sensor.cpp, sdk/src/connections/usb/linux/usb_depth_sensor_linux.cpp
=> sdk/connections/usb/usb_depth_sensor_linux.cpp: fix frame size

sdk/src/cameras/itof-camera/mode_info.cpp, sdk/src/connections/target/adsd3100_sensor.h
=> sdk/src: add lt_bin frame type

sdcard-images-utils/nxp/patches/linux-imx/0024-drivers-media-spi-addicmos-Fix-resolution-for-QVGA-m.patch, sdcard-images-utils/nxp/patches/linux-imx/0025-drivers-media-addicmos-Reduce-line-width-for-QVGA-mo.patch
=> sdcard-image-utils: patches: linux-imx: Patches for QVGA mode support

examples/data_collect/main.cpp
=> examples: data_collect: Add mode 1 to data_collect

sdcard-images-utils/nxp/patches/ubuntu_overlay/step1/usr/share/systemd/uvc-gadget.sh
=> sdcard-images-utils: ubuntu_overlay: uvc-gadget.sh: Add mode1 resolution

CMakeLists.txt
=> cmake: Increase project version from 2.0.0 to 2.1.0
